<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Median test. Multiple comparisons — Median.test • agricolae</title>


<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<!-- Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/united/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous" />


<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.1/css/all.min.css" integrity="sha256-PbSmjxuVAzJ6FPvNYsrXygfGhNJYyZ2GktDbkMBqQZg=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.1/css/v4-shims.min.css" integrity="sha256-A6jcAdwFD48VMjlI3GDxUd+eCQa7/KWy6G9oe/ovaPA=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script>

<!-- headroom.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>


<!-- docsearch -->
<script src="../docsearch.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous" />
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>



<meta property="og:title" content="Median test. Multiple comparisons — Median.test" />
<meta property="og:description" content="A nonparametric test for several independent samples. The median test is designed
  to examine whether several samples came from populations having the same median." />
<meta name="twitter:card" content="summary" />




<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-116716530-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-116716530-2');
</script>


  </head>

  <body>
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">agricolae</a>
        <span class="version label label-danger" data-toggle="tooltip" data-placement="bottom" title="Unreleased version">1.3.3</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
    Home
  </a>
</li>
<li>
  <a href="../reference/index.html">
    <span class="fa fa-code"></span>
     
    Reference
  </a>
</li>
<li>
  <a href="../articles/Introagricolae.html">
    <span class="fa fa-file-o"></span>
     
    Tutorial
  </a>
</li>
<li>
  <a href="../news/index.html">
    <span class="fa fa-newspaper-o"></span>
     
    News
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/myaseen208/agricolae">
    <span class="fa fa-github-alt"></span>
     
    Github
  </a>
</li>
      </ul>
      
      <form class="navbar-form navbar-right hidden-xs hidden-sm" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
        </div>
      </form>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      

      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Median test. Multiple comparisons</h1>
    
    <div class="hidden name"><code>median.rd</code></div>
    </div>

    <div class="ref-description">
    <p>A nonparametric test for several independent samples. The median test is designed
  to examine whether several samples came from populations having the same median.</p>
    </div>

    <pre class="usage"><span class='fu'><a href='median.rd.html'>Median.test</a></span>(<span class='no'>y</span>,<span class='no'>trt</span>,<span class='kw'>alpha</span><span class='kw'>=</span><span class='fl'>0.05</span>,<span class='kw'>correct</span><span class='kw'>=</span><span class='fl'>TRUE</span>,<span class='kw'>simulate.p.value</span> <span class='kw'>=</span> <span class='fl'>FALSE</span>, <span class='kw'>group</span> <span class='kw'>=</span> <span class='fl'>TRUE</span>,
<span class='kw'>main</span> <span class='kw'>=</span> <span class='kw'>NULL</span>,<span class='kw'>console</span><span class='kw'>=</span><span class='fl'>TRUE</span>)</pre>

    <h2 class="hasAnchor" id="arguments"><a class="anchor" href="#arguments"></a>Arguments</h2>
    <table class="ref-arguments">
    <colgroup><col class="name" /><col class="desc" /></colgroup>
    <tr>
      <th>y</th>
      <td><p>Variable response</p></td>
    </tr>
    <tr>
      <th>trt</th>
      <td><p>Treatments</p></td>
    </tr>
    <tr>
      <th>alpha</th>
      <td><p>error type I</p></td>
    </tr>
    <tr>
      <th>correct</th>
      <td><p>a logical indicating whether to apply continuity correction
  when computing the test statistic for 2 groups. The correction will not be bigger
  than the differences themselves. No correction is done if simulate.p.value = TRUE.</p></td>
    </tr>
    <tr>
      <th>simulate.p.value</th>
      <td><p>a logical indicating whether to compute p-values by
  Monte Carlo simulation</p></td>
    </tr>
    <tr>
      <th>group</th>
      <td><p>TRUE or FALSE</p></td>
    </tr>
    <tr>
      <th>main</th>
      <td><p>Title</p></td>
    </tr>
    <tr>
      <th>console</th>
      <td><p>logical, print output</p></td>
    </tr>
    </table>

    <h2 class="hasAnchor" id="details"><a class="anchor" href="#details"></a>Details</h2>

    <p>The data consist of k samples of possibly unequal sample size.<br />
Greater: is the number of values that exceed the median of all data and <br />
LessEqual: is the number less than or equal to the median of all data.</p>
    <h2 class="hasAnchor" id="value"><a class="anchor" href="#value"></a>Value</h2>

    <p></p>
<dt>statistics</dt><dd><p>Statistics of the model</p></dd>
  <dt>parameters</dt><dd><p>Design parameters</p></dd>
  <dt>medians</dt><dd><p>Statistical summary of the study variable</p></dd>
  <dt>comparison</dt><dd><p>Comparison between treatments</p></dd>
  <dt>groups</dt><dd><p>Formation of treatment groups</p></dd>

    <h2 class="hasAnchor" id="references"><a class="anchor" href="#references"></a>References</h2>

    <p>Practical Nonparametrics Statistics. W.J. Conover, 1999</p>
    <h2 class="hasAnchor" id="see-also"><a class="anchor" href="#see-also"></a>See also</h2>

    <div class='dont-index'><p><code><a href='BIB.test.html'>BIB.test</a></code>, <code><a href='DAU.test.html'>DAU.test</a></code>, <code><a href='duncan.test.html'>duncan.test</a></code>,
  <code><a href='durbin.test.html'>durbin.test</a></code>, <code><a href='friedman.html'>friedman</a></code>, <code><a href='HSD.test.html'>HSD.test</a></code>,
  <code><a href='kruskal.html'>kruskal</a></code>, <code><a href='LSD.test.html'>LSD.test</a></code>, <code><a href='PBIB.test.html'>PBIB.test</a></code>, 
  <code><a href='REGW.test.html'>REGW.test</a></code>, <code><a href='scheffe.test.html'>scheffe.test</a></code>, <code><a href='SNK.test.html'>SNK.test</a></code>,
  <code><a href='VanderWarden.html'>waerden.test</a></code>, <code><a href='waller.test.html'>waller.test</a></code>, <code><a href='plot.group.html'>plot.group</a></code></p></div>

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'><span class='fu'><a href='https://rdrr.io/r/base/library.html'>library</a></span>(<span class='no'>agricolae</span>)
<span class='co'># example 1</span>
<span class='fu'><a href='https://rdrr.io/r/utils/data.html'>data</a></span>(<span class='no'>corn</span>)
<span class='no'>out</span><span class='kw'>&lt;-</span><span class='fu'><a href='https://rdrr.io/r/base/with.html'>with</a></span>(<span class='no'>corn</span>,<span class='fu'><a href='median.rd.html'>Median.test</a></span>(<span class='no'>observation</span>,<span class='no'>method</span>,<span class='kw'>console</span><span class='kw'>=</span><span class='fl'>FALSE</span>))
<span class='no'>z</span><span class='kw'>&lt;-</span><span class='fu'><a href='bar.err.html'>bar.err</a></span>(<span class='no'>out</span>$<span class='no'>medians</span>,<span class='kw'>variation</span> <span class='kw'>=</span> <span class='st'>"range"</span>,<span class='kw'>ylim</span><span class='kw'>=</span><span class='fu'><a href='https://rdrr.io/r/base/c.html'>c</a></span>(<span class='fl'>0</span>,<span class='fl'>120</span>),
           <span class='kw'>space</span><span class='kw'>=</span><span class='fl'>2</span>,<span class='kw'>border</span><span class='kw'>=</span><span class='fl'>4</span>,<span class='kw'>col</span><span class='kw'>=</span><span class='fl'>3</span>,<span class='kw'>density</span><span class='kw'>=</span><span class='fl'>10</span>,<span class='kw'>angle</span><span class='kw'>=</span><span class='fl'>45</span>)</div><div class='img'><img src='median-1.png' alt='' width='700' height='433' /></div><div class='input'><span class='co'># example 2</span>
<span class='no'>out</span><span class='kw'>&lt;-</span><span class='fu'><a href='https://rdrr.io/r/base/with.html'>with</a></span>(<span class='no'>corn</span>,<span class='fu'><a href='median.rd.html'>Median.test</a></span>(<span class='no'>observation</span>,<span class='no'>method</span>,<span class='kw'>console</span><span class='kw'>=</span><span class='fl'>FALSE</span>,<span class='kw'>group</span><span class='kw'>=</span><span class='fl'>FALSE</span>))
<span class='fu'><a href='https://rdrr.io/r/base/print.html'>print</a></span>(<span class='no'>out</span>$<span class='no'>comparison</span>)</div><div class='output co'>#&gt;         median     chisq pvalue signif.
#&gt; 1 and 2   89.0  2.554444 0.1100        
#&gt; 1 and 3   92.5  6.349206 0.0117       *
#&gt; 1 and 4   83.0 13.432099 0.0002     ***
#&gt; 2 and 3   91.0 13.246753 0.0003     ***
#&gt; 2 and 4   82.5 14.400000 0.0001     ***
#&gt; 3 and 4   82.0 15.000000 0.0001     ***</div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">
    <h2>Contents</h2>
    <ul class="nav nav-pills nav-stacked">
      <li><a href="#arguments">Arguments</a></li>
      <li><a href="#details">Details</a></li>
      <li><a href="#value">Value</a></li>
      <li><a href="#references">References</a></li>
      <li><a href="#see-also">See also</a></li>
      <li><a href="#examples">Examples</a></li>
    </ul>

    <h2>Author</h2>
    <p>Felipe de Mendiburu</p>
  </div>
</div>


      <footer>
      <div class="copyright">
  <p>Developed by Felipe de Mendiburu.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.9000.</p>
</div>

      </footer>
   </div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script>
<script>
  docsearch({
    
    
    apiKey: 'bdafb7ea4490644e670f470ee3ef537f',
    indexName: 'agricolae',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>



  </body>
</html>


